#!/bin/sh

if [ "$(entropy_level)" -lt "1000" ]; then
    echo "Entropy pool is low.  Attempting to run haveged..."
    echo "Container requirement: --cap-add SYS_ADMIN"
    haveged
else
    echo "Entropy pool is good.  Fill not required."
fi
