#!/bin/sh

# Draining the entropy pool will force haveged to
# fill it on startup.  This is desirable because
# if it fails it will be known immediately.
entropy_drain

haveged -F -v -1

# If haveged fails you'll see this message.
echo
echo "Docker container requirement: --cap-add SYS_ADMIN"
