#!/bin/sh

# Draining the entropy pool will force haveged
# to fill it on startup.  This means you'll know
# immediately if haveged fails.
entropy_drain

haveged -F -v -1

# This message is hidden if haveged is successfully
# running in the foreground.
echo
echo "Docker container requirement: --cap-add SYS_ADMIN"
