#!/bin/sh

# Make sure the entropy pool is drained so that
# haveged will attempt to fill it on startup.
entropy_drain

haveged -F -v -1

# If haveged fails you'll see this message.
echo
echo "Docker container requirement: --cap-add SYS_ADMIN"
